services:
  - type: web
    name: prometeylabs-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_server:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --keep-alive 2
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/prometeylabs_bot
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: KEEP_ALIVE
        value: "true"
    healthCheckPath: /
    autoDeploy: true
